name: elegant
description: A collection of utility functions and classes.
version: 1.0.0
repository: https://github.com/alexobviously/elegant

environment:
  sdk: ^3.10.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
